## YEML (YAML ExE Boss Extended Markup Language) Site Configuration.
title:	ExE Boss
author:	ExE Boss
baseurl:	""
description:	The Thing with the Stuff and the Things

google-verification:
    # .tech
    - HRq8Wf-4eZ9CYvzExrFfEHlhYXX73y6joWldaG8c0Ck
    # .GitHub.io
    - VS6KpGeBeGjd_unYt62B8FZikoetJnCgZYFvxzLZHeU

wot-verification:
    # .tech
    - 97197d01470529e7d990
    # .GitHub.io
    - 7007b782633555338dfc

defaults:
    -
        scope:
            path:	""
        values:
            layout:	"default"
            include_footer:	true

# WHO IN THE F# (the programming language) DOESN'T SUPPORT TABS IN 2017? '	' <- tab
# P.S.: F# (the programming language) also doesn't support tabs, and that's terrible
